# Generated by Django 3.2.4 on 2021-09-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotesModel',
            fields=[
                ('SrNo', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
